### ISSUE TITLE
About Consistency Energy Maximization loss

### ISSUE THREAD

**Issue by forence** [luogen1996/MCN#1]
Hi Gen Luo,

It's a great job and I enjoy reading your paper very much!

I really did not understand the meaning of the formula at first, until I read some interpretations(artcle) in the website based on the gain and phase margin. 

I want to know how did you think of constructing such a CEM loss function？

**Comment by luogen1996** [comment]
Thanks for your appreciation! It's better to send me a email to make further discussions. I will reply to you  in detail.
