### ISSUE TITLE
About the pretrained weights link

### ISSUE THREAD

**Issue by obin-hero** [luogen1996/MCN#3]
Hello, I just read your paper and thanks for sharing the source code of this great work!

I want to reproduce your work, but the pretrained weights download link is not working.
I think this one-drive link is kind of unstable.. download button shows up, but it doesn't respond anything.
Can you check the link, please? 

Thank you.

**Comment by luogen1996** [comment]
> Hello, I just read your paper and thanks for sharing the source code of this great work!
> 
> I want to reproduce your work, but the pretrained weights download link is not working.
> I think this one-drive link is kind of unstable.. download button shows up, but it doesn't respond anything.
> Can you check the link, please?
> 
> Thank you.

We have replaced the invalid one-drive link, please feel free to download from it.
