### ISSUE TITLE
pretrained weight

### ISSUE THREAD

**Issue by xxd1999** [luogen1996/MCN#4]
Hello.It seemed like the link is invalid  in my computer,does anyone download the weight successfully?

**Comment by luogen1996** [comment]
> Hello.It seemed like the link is invalid in my computer,does anyone download the weight successfully?

We have checked the links and solved it. All pretrained models and logs are available now.

**Comment by xxd1999** [comment]
> > Hello.It seemed like the link is invalid in my computer,does anyone download the weight successfully?
> 
> We have checked the links and solved it. All pretrained models and logs are available now.

Thanks.

**Comment by AngelYang23** [comment]
Hello, it appears that the link is not working on my computer as well. Could you please double-check its validity?

**Comment by luogen1996** [comment]
> Hello, it appears that the link is not working on my computer as well. Could you please double-check its validity?

I'm sure that the link is still available. You may need to use VPN to download the files.

**Comment by AngelYang23** [comment]
Thank you for your suggestions.The website works well.
