### ISSUE TITLE
The detail version of  the lib in requirments

### ISSUE THREAD

**Issue by qiqi545** [luogen1996/MCN#5]
When I try to exec the data_process.py, there is a fetal error “Process finished with exit code -1073740940 (0xC0000374)” occured on the sentence "mask.decode(rle)" in  getmask of refer.py. But   no detail exception info or tip info. So, I hope that you can provide the version of scikit-image,numpy,pycocotools.

**Comment by luogen1996** [comment]
> When I try to exec the data_process.py, there is a fetal error “Process finished with exit code -1073740940 (0xC0000374)” occured on the sentence "mask.decode(rle)" in getmask of refer.py. But no detail exception info or tip info. So, I hope that you can provide the version of scikit-image,numpy,pycocotools.

```
pycocotools==2.0.0
matplotlib==3.0.2
numpy==1.15.4
scikit-image==0.14.2
opencv==3.4.2
keras_bert
progressbar2==3.37.1
spacy==2.0.16
keras==2.2.4
tensorflow-gpu==1.9.0
```
Please refer to 'requirements.txt', we have updated it. The codes are worked well under python 3.6.6 and python 3.7 (python >3.0 will be ok i guess).

**Comment by qiqi545** [comment]
Thanks

**Comment by qiqi545** [comment]
Now, the problem still exists. My system is win10, and I installed the vs 2015.  May I install vs2017?

**Comment by luogen1996** [comment]
> Now, the problem still exists. My system is win10, and I installed the vs 2015. May I install vs2017?

pycocotools may not work well in windows.  you can try to generate the annoations under Ubuntu environment and the problem will be solved.

**Comment by qiqi545** [comment]
OK，thank you.
